### ISSUE TITLE
getPassword breaks bufio.ReadString after its called.

### ISSUE THREAD

**Issue by Maddog2050** [howeyc/gopass#28] opened 2016-03-17 17:15 UTC
After getPassword has been called, any subsequent calls to bufio.ReadString fail to read any data and stop the program from continuing on once called. It even prevents Ctrl+C from terminating the program.

**Comment by johnSchnake** [comment] 2016-03-20 17:16
Could you provide an example; maybe I don't fully understand the situation you are referring to? I have apps that get lots of output from the user after getting a password early on.  Here is a simple test using bufio.ReadString like you mentioned and it works fine.

```
package main

import (
	"bufio"
	"fmt"
	"os"

	"github.com/howeyc/gopass"
)

func main() {
       // Get password first
	p, err := gopass.GetPasswdMasked()
	fmt.Println("gotpass:", string(p), err)

        // Can still read from os.Stdin (using bufio as specifically mentioned in issue)
	r := bufio.NewReader(os.Stdin)
	s, err := r.ReadString('\n')
	fmt.Println("read:", s, err)
}
```

**Comment by chambbj** [comment] 2016-04-05 18:32
@johnSchnake I can replicate this issue, even with your example code. The catch here is that it is only on Windows. Everything seems to be fine on OS X.

My currently installed Go version is:
```
go version go1.5beta1 windows/amd64
```

I see the same thing when trying to run `ReadPassword` directly in `golang.org/x/crypto/ssh/terminal`, so I'm thinking this is a platform-specific issue in terminal that has trickled down to gopass.

**Comment by johnSchnake** [comment] 2016-04-06 15:11
Thanks for following up on this!  It was bugging me so I tried a few things, and found a bug in the terminal code for Windows.

https://github.com/golang/crypto/blob/master/ssh/terminal/util_windows.go#L84-L95

Notice that it _should_ be returning the original state, like getState() but it modifies it to make it "raw" then returns that.  I will go about trying to get that library fixed; if it is taking a while then we may need to just do a work around (very easy to do, just need to run GetState() and restore _that_ mode, not the mode returned from makeRaw).

**Comment by johnSchnake** [comment] 2016-04-06 18:07
https://github.com/golang/go/issues/15155 opened and I submitted a PR for it.  Not sure how long that might take, its a small change though (2 modified lines)

**Comment by johnSchnake** [comment] 2016-04-08 16:36
Merged! should be good to go now.  Confirmed it works on my Windows machine after I ran `git pull` on that repo.

**Comment by chambbj** [comment] 2016-04-08 17:35
Confirmed here too. Thanks for the upstream fix!

**Comment by johnSchnake** [comment] 2016-04-08 19:29
@chambbj or @howeyc can you mark this issue as closed?

**Closed** 2016-04-09 00:28 UTC
